apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../apps/flask-app/deployment.yaml
  - ../../apps/microservice-1/deployment.yaml
  - ../../apps/microservice-2/deployment.yaml

replicas:
  - name: flask-app
    count: 1
  - name: user-service
    count: 1
  - name: product-service
    count: 1

images:
  - name: localhost:30500/flask-app
    newTag: latest
  - name: localhost:30500/user-service
    newTag: latest
  - name: localhost:30500/product-service
    newTag: latest

commonLabels:
  environment: dev
  managed-by: argocd
